### ISSUE TITLE
Add support for Sets

### ISSUE THREAD

**Issue by jpbetz** [coursera/courier#2]
Developers often want to represent a set in Courier.

Currently, the only available approach is to use a Pegasus `array` and transform it to/from a Scala Set manually.

Adding an option in our .pdsc files that developer could use to specify the desired binding type, e.g.:

```
{ "type": "array", "items": "Example", "scala": { "type": "set" } }
```

Would allow us to generate an appropriate Set binding class.

**Comment by eeasley-coursera** [comment]
Support for non-empty lists would also often be useful.

**Comment by jpbetz** [comment]
closing hopelessly stale issues I've opened
