### ISSUE TITLE
Improved "JSON Equivalent" binary protocol support

### ISSUE THREAD

**Issue by jpbetz** [coursera/courier#4]
There are a number of binary protocols that provide "JSON equivalent" semantics:
- PSON (non-standard pegasus codec)
- BSON (mongoDB)
- UBJSON
- Smile
- CBOR (not sure this is entirely JSON equivalent)
- Flatbuffers
- ???

We should carefully review the performance of these (https://github.com/eishay/jvm-serializers/wiki is a good start) and determine which is the best and add codec support to Courier for that protocol.

Pegasus already includes support for PSON and BSON, so we really only need to review UBJSON, Smile, CBOR or any other contenders and determine if they are better than PSON or BSON, and if so, add codec support.

**Comment by karthikrg** [comment]
How about flatbuffers?

**Comment by jpbetz** [comment]
@karthikrg Yes, Flatbuffers look's excellent.  I've updated the above list to include them.

**Comment by jpbetz** [comment]
closing hopelessly stale issues I've opened
