### ISSUE TITLE
Make a release?

### ISSUE THREAD

**Issue by eboto** [coursera/courier#7]
I noticed that `unapply` on unions was added in September, and so it is not part of the current 0.4.1. Can we get a `0.12.3` release into sonatype?

**Comment by saeta** [comment]
Looks like there's at least 0.7.1 in central (http://mvnrepository.com/artifact/org.coursera.courier/courier-runtime_2.11/0.7.1). @jpbetz could you cut a new release into maven central soon?

**Comment by jpbetz** [comment]
0.12.3 released.
