### ISSUE TITLE
Prototype a grammar for Courier

### ISSUE THREAD

**Issue by jpbetz** [coursera/courier#9]
We’ve used the .pdsc file format up to this point for Pegasus schemas for a few reasons:
- It’s already been implemented, stable and well tested
- The extensibility of JSON has proven very convenient. We have been able to add a number of custom properties to schemas (“defaultNone”, “isTranslatable”, “scala.class” …)

However, writing JSON by hand has some limitations:
- Verbosity makes authoring new schemas somewhat annoying/unpleasant
- JSON syntax “gets in the way”, reducing readability
- All doc strings must be a single line

And the .pdsc JSON structure has a number of warts as well:
- Maps and arrays must be declared using an inconvenient “type”: { “type”: “array”, … } format
  “defaultNone” feels bolted on
- All references to types not in the same namespace must be fully qualified
## Proposed .courier Grammar

We have a few goals for a grammar:
- Retains extensibility of .pdsc format:  All types and fields may be extensible with arbitrary data (which must either be JSON or be fully isomorphic with JSON).
- The mapping between the grammar and the .pdsc format must be clear and direct (unless there is a \* VERY compelling reason not to). This implies that we should continue to use the same keywords used in the .pdsc format unless there is a compelling reason not to.
- Foster consistent style: keywords should be lowercase, developer defined types should be PascalCase, field names should be camelCase
- Provide a Scala / Swift friendly syntax, also make use of syntax from GraphQL, JSON and HOCON as appropriate
- Support multi-line markdown style documentation strings
- Eliminate most (ideally all) cruft found in the .pdsc format

Examples:

```
namespace org.coursera.fortune
include org.coursera.models.common.DateTime

/** A fortune. */
record Fortune {
  @{ "isTranslatable": true }
  title: string,
  /** The fortune telling. */
  telling: FortuneCookie | MagicEightBall | string // a union
  createdAt: DateTime? = nil // optional defaulted to nil/None

}
```

```
namespace org.coursera.fortune

enum MagicEightBallAnswer {
  IT_IS_CERTAIN
  /** Where later is at least 10 ms from now. */
  ASK_AGAIN_LATER
  OUTLOOK_NOT_SO_GOOD
}
```

```
namespace org.coursera.fortune

record FortuneCookie {
  ...SomeRecord // include fields from another record
  luckyNumbers: array[int]
  exampleMap: map[int, string]
}
```

```
namespace org.coursera.models.common

/** ISO 8601 date-time. */
@{
  "scala": {
    "class": "org.joda.time.DateTime",
    "coercerClass": "org.coursera.models.common.DateTimeCoercer"
  }
}
typeref DateTime = string
```
## Grammar

Features:
- namespaces and includes at top of file
- C-style comments: `/* */` and `//`
- `/** */` style doc strings, but with markdown support
- Declare parameters using: `<identifier> ":" <type> (= <default>)?`
- Default values will be JSON literals: `“a string”`, `1`, `3.14`, `true`, ... , `[ … ]`, `{ … }`
- Declare generic types in `<type>[<typeParams>]` syntax
- Insignificant commas (?)
- Properties expressed using annotation style syntax (`@...`)
- Swift style optional type declarations: `<type> “?”`(Alternatively we could use Scala style instead, e.g. optional[<type>])
- Uniform GADT (generic algebraic data type) representation: `<type>[<typeParams>]`.  We will use this for maps (`map[key, value]`) arrays (`array[items]`) and unions (`union[Member1, Member2, ...]`) and may the syntax user defined generic types in the future.
- GraphQL fragment style includes: …<type>
## Markdown
- We will start with a “Vanilla” markdown format that is compatible with both Scaladoc and Swift doc strings.
## IDE Support
- IntelliJ “Custom Language Support” Plugin. Initially we need at least Lexer/Parser/Syntax Highlighter support, but if it’s not too much work, we should go for comprehensive integration.
## Future Work
- Includes
- Multiple schema definitions per file
- Markdown references (and appropriate conversion to Scaladoc and Swift doc strings)

**Comment by saeta** [comment]
@jpbetz for doc strings, will you support doc strings with a left margin of asterisks? i.e. comments formatted as follows:

```
namespace org.coursera.fortune
include org.coursera.models.common.DateTime

/**
 * A fortune
 *
 * This forward-looking type helps encapsulate key details regarding
 * the future of potential subjects including, ... well, you.
 */
record Fortune {
  @{ "isTranslatable": true }
  title: string,
  /** The fortune telling. */
  telling: FortuneCookie | MagicEightBall | string // a union
  createdAt: DateTime? = nil // optional defaulted to nil/None
}
```

Relatedly, when designing a formatter / linter, how about a default line length limit. :-)

**Comment by jpbetz** [comment]
@eboto You may be interested in this.  We're currently doing our prototyping on the https://github.com/coursera/courier/tree/grammar branch.

Here's what it looks like in IntelliJ so far:

<img width="502" alt="screen shot 2015-10-19 at 4 11 19 pm" src="https://cloud.githubusercontent.com/assets/523590/10593851/1e61f894-767c-11e5-9b34-4b0b95c971c6.png">

<img width="604" alt="screen shot 2015-10-19 at 4 12 45 pm" src="https://cloud.githubusercontent.com/assets/523590/10593870/45ee5d94-767c-11e5-9e25-7f00e3cfdd06.png">

Any thoughts/feedback you have would be very helpful.

**Comment by jpbetz** [comment]
@saeta You mean like this https://github.com/coursera/courier/blob/grammar/grammar/src/main/scala/org/coursera/courier/grammar/CourierParser.scala#L203 ?  Done :)

Linter is a good idea.

**Comment by saeta** [comment]
@jpbetz yup, exactly like that. :-)

**Comment by jpbetz** [comment]
This is available and documentation has been updated to include information on how to use it.
